name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Microservices
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - UserManagementService
          - DesignRepositoryService
          - CommunicationService
          - FurnitureLibraryService
          - PaymentService

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore ${{ matrix.service }}/*.sln

      # Build the solution
      - name: Build
        run: dotnet build ${{ matrix.service }}/*.sln --no-restore --configuration Release

      # Run tests (if applicable)
      - name: Test
        run: dotnet test ${{ matrix.service }}/*.Tests/*.csproj --no-build --configuration Release

