name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Microservices
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - UserManagementService
          - DesignRepositoryService
          - CommunicationService
          - FurnitureLibraryService
          - PaymentService

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      # Login to DockerHub (Optional, if pushing images to DockerHub)
      - name: Login to DockerHub
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore ${{ matrix.service }}/*.sln

      # Build the solution
      - name: Build
        run: dotnet build ${{ matrix.service }}/*.sln --no-restore --configuration Release

      # Run tests (if applicable)
      - name: Test
        run: |
          if [ -d "${{ matrix.service }}/Tests" ]; then
            dotnet test ${{ matrix.service }}/*.Tests/*.csproj --no-build --configuration Release
          else
            echo "No tests found for ${{ matrix.service }}."
          fi

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t myrepo/${{ matrix.service }}:latest ${{ matrix.service }}/

      # Push Docker Image to DockerHub
      - name: Push Docker Image
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        run: |
          docker push myrepo/${{ matrix.service }}:latest
